export const educationLogos = [
    { name: "ALCALDIA DE SANTA CRUZ DE LORICA" },
    { name: "ALCALDIA MAYOR DE CARTAGENA DE INDIAS" },
    { name: "ALCALDIA MUNICIPAL DE VALLEDUPAR" },
    { name: "DEPARTAMENTO DE BOLIVAR - SECRETARIA DE EDUCACION DE BOLIVAR" },
    { name: "DEPARTAMENTO DE CUNDINAMARCA (SED CUNDINAMARCA)" },
    { name: "DISTRITO DE TURBO ANTIOQUIA EXTRA (SEM TURBO)" },
    { name: "FONDO EDUCATIVO DEPARTAMENTAL DEL MAGDALENA (SED MAGDALENA)" },
    { name: "GOBERNACION DE BOLIVAR" },
    { name: "GOBERNACION DE SUCRE (SED SUCRE)" },
    { name: "MUNICIPIO DE MEDELLIN / SECRETARIA DE EDUCACION DE MEDELLIN" },
    { name: "SECRETARIA DE EDUCACION DE LA GUAJIRA" },
    { name: "SECRETARIA DE EDUCACION DE MONTERIA" },
    { name: "SECRETARIA DE EDUCACION DEL CESAR YADIB / YADIB1" },
    { name: "SECRETARIA DE EDUCACION DEPARTAMENTAL DE RISARALDA" },
    { name: "SECRETARIA DE EDUCACION MUNICIPAL DE CIENAGA MAGDALENA" },
    { name: "SECRETARIA DE EDUCACION MUNICIPAL DE VALLEDUPAR" },
    { name: "SECRETARIA DE EDUCACION MUNICIPAL URIBIA" },
    { name: "SED ANTIOQUIA" },
    { name: "SED BARRANQUILLA" },
    { name: "SED CARTAGENA" },
    { name: "SED CHOCO" },
    { name: "SED NORTE DE SANTANDER" },
    { name: "SEM SAHAGUN" },
];

export const pensionLogos = [
    { name: "Asulado seguros de vida" },
    { name: "Bbva seguros" },
    { name: "Colfondos" },
    { name: "Colpensiones" },
    { name: "Compañía de seguros bolívar" },
    { name: "Consorcio fopep (Aparece también como Fondo de Pensiones Públicas Nivel Nacional)" },
    { name: "Fiduprevisora" },
    { name: "Global seguros de vida S.A." },
    { name: "Mapfre colombia" },
    { name: "Mapfre pensionados" },
    { name: "Porvenir" },
    { name: "Protección S.A." },
    { name: "Seguros alfa" },
    { name: "Skandia" },
];

export const fuerzaPublicaLogos = [
    { name: "CREMIL / MD CREMIL (Caja de Retiro de las Fuerzas Militares)" },
    { name: "CASUR (Caja de Sueldos de Retiro de la Policía)" },
    { name: "CAGEN (Caja General de la Policía Nacional)" },
    { name: "TEGEN" },
    { name: "MINDEFENSA" },
];
